package com.urlshortener.dto.ai;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "AI analysis result for a URL")
public class AiAnalysisResult {

    @Schema(description = "AI-generated summary of the URL content", example = "A popular code hosting platform for version control")
    private String summary;

    @Schema(description = "AI-determined category", example = "Technology")
    private String category;

    @Schema(description = "AI-generated tags", example = "[\"programming\", \"git\", \"open-source\"]")
    private List<String> tags;

    @Schema(description = "Safety score from 0.0 (unsafe) to 1.0 (safe)", example = "0.95")
    private BigDecimal safetyScore;

    @Schema(description = "Whether the URL is considered safe", example = "true")
    private Boolean isSafe;

    @Schema(description = "Reasons if URL is flagged as potentially unsafe")
    private List<String> safetyReasons;

    @Schema(description = "Custom alias suggestions generated by AI")
    private List<String> aliasSuggestions;

    @Schema(description = "Whether analysis was retrieved from cache")
    private Boolean fromCache;
}

